name: receipt_manager
description: A receipt management app.
publish_to: 'none'
version: 3.1.1+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  jwt_decoder: ^2.0.1
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  intl: ^0.18.1
  logger: ^2.0.1
  flutter_svg: ^2.0.7
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.1.14
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  universal_html: ^2.2.4
  image_picker_web: ^3.1.1
  url_strategy: ^0.2.0
  flutter_web_plugins:
    sdk: flutter
  geolocator: 9.0.2
  geocoding: ^2.1.0
  camera: ^0.10.5+9
  fl_chart: ^0.65.0
  flutter_exif_rotation: ^0.5.2
  permission_handler: ^11.0.1
  device_info_plus: ^11.4.0
  file_picker: ^10.1.9
  syncfusion_flutter_pdfviewer: ^29.2.7
  geolocator_apple: 2.2.7
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/assets/icon/app_icon.png"
  adaptive_icon_background: "#7E5EFD"
  adaptive_icon_foreground: "lib/assets/icon/app_icon.png"

flutter_native_splash:
  color: "#7E5EFD"
  image: "lib/assets/icon/app_icon.png"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - lib/assets/apple.png
    - lib/assets/google.png
    - lib/assets/facebook.png
    - lib/assets/icon/

