name: receipt_manager
description: A receipt management app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  jwt_decoder: ^2.0.1
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  intl: ^0.18.1
  logger: ^2.0.1
  flutter_svg: ^2.0.7
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.1.14
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  universal_html: ^2.2.4
  image_picker_web: ^3.1.1
  url_strategy: ^0.2.0
  flutter_web_plugins:
    sdk: flutter
  geolocator: ^9.0.2
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/apple.png
    - lib/assets/google.png
    - lib/assets/facebook.png

