// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDnu1LVQsSzIRpDBw4xCD49VC6aOiwNipM",
    authDomain: "managereceiptcom.firebaseapp.com",
    projectId: "managereceiptcom",
    storageBucket: "managereceiptcom.firebasestorage.app",
    messagingSenderId: "964886436743",
    appId: "1:964886436743:web:18e259afc2f197605ed122",
    measurementId: "G-TYVYHQSG6L",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGhVo-1LhAzUq3o4hC2P6wE3Ho9IgYnMY',
    appId: '1:964886436743:android:006165b5e177d45c5ed122',
    messagingSenderId: '964886436743',
    projectId: 'managereceiptcom',
    storageBucket: 'managereceiptcom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIfad1v5ZRx0E--lSlkja45NkI9wdX2cw', // You need to get this from Firebase Console
    appId: '1:964886436743:ios:4245a75f7a3cc0a95ed122', // You need to get this from Firebase Console
    messagingSenderId: '964886436743',
    projectId: 'managereceiptcom',
    storageBucket: 'managereceiptcom.firebasestorage.app',
    iosBundleId: 'com.ButterflyTchnology.managereceipt',
  );
}
